// Code generated by MockGen. DO NOT EDIT.
// Source: routes/rest-api.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAwsIPRangeRestAPI is a mock of AwsIPRangeRestAPI interface
type MockAwsIPRangeRestAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAwsIPRangeRestAPIMockRecorder
}

// MockAwsIPRangeRestAPIMockRecorder is the mock recorder for MockAwsIPRangeRestAPI
type MockAwsIPRangeRestAPIMockRecorder struct {
	mock *MockAwsIPRangeRestAPI
}

// NewMockAwsIPRangeRestAPI creates a new mock instance
func NewMockAwsIPRangeRestAPI(ctrl *gomock.Controller) *MockAwsIPRangeRestAPI {
	mock := &MockAwsIPRangeRestAPI{ctrl: ctrl}
	mock.recorder = &MockAwsIPRangeRestAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockAwsIPRangeRestAPI) EXPECT() *MockAwsIPRangeRestAPIMockRecorder {
	return m.recorder
}

// Download mocks base method
func (m *MockAwsIPRangeRestAPI) Download() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download
func (mr *MockAwsIPRangeRestAPIMockRecorder) Download() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockAwsIPRangeRestAPI)(nil).Download))
}
