name: CICD

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: Run build
      run: go build . 
      
    - name: Run vet & lint
      run: |
        mkdir -p output
        go vet -all ./... 2> output/govet-report.out
        golint -set_exit_status `go list ./...` > output/golint-report.out
    
    - name: Run testing
      run: go test ./... -cover -coverprofile=output/coverage.out -json > output/unit-test-report.json
  
  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ contains(github.ref, 'refs/tags/v') && github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.0

      - name: Import GPG key
        id: import_gpg
        uses: paultyng/ghaction-import-gpg@v2.1.0
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}